jobs:
- name: jeopardy
  tasks:
  - tap-pixlet--jeopardy target-tidbyt
- name: jeopardy--webp
  tasks:
  - tap-pixlet--jeopardy target-webp

plugins:
  extractors:
  - name: tap-pixlet--jeopardy
    inherit_from: tap-pixlet
    config:
      path: apps/jeopardy
